In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('world_alcohol - world_alcohol.csv')

In [5]:
filtered_df_avg_consumption = df[(df['Display Value'] >= 0.5) & (df['Display Value'] <= 2.5)]

filtered_df_avg_consumption

,Year,WHO region,Country,Beverage Types,Display Value
1,1986,Americas,Uruguay,Other,0.50
2,1985,Africa,Cte d'Ivoire,Wine,1.62
4,1987,Americas,Saint Kitts and Nevis,Beer,1.98
8,1986,Americas,Antigua and Barbuda,Spirits,1.55
11,1989,Americas,Guatemala,Beer,0.62
17,1989,Africa,Seychelles,Beer,2.23
18,1984,Europe,Norway,Spirits,1.62
19,1984,Africa,Kenya,Beer,1.08
26,1985,Europe,United Kingdom of Great Britain and Northern I...,Wine,1.36
27,1984,Eastern Mediterranean,Bahrain,Beer,2.22
32,1989,Africa,Mauritius,Beer,1.60
34,1986,Europe,Russian Federation,Wine,0.80
35,1985,Americas,Saint Kitts and Nevis,Spirits,2.24
40,1987,Europe,Austria,Spirits,1.90
46,1987,Americas,Trinidad and Tobago,Spirits,2.26
48,1987,Americas,Nicaragua,Beer,0.70
49,1986,Europe,Malta,Wine,1.49
54,1984,Americas,El Salvador,Spirits,1.81
64,1989,Americas,Bolivia (Plurinational State of),Beer,1.26
70,1986,Africa,Madagascar,Spirits,1.02
71,1985,Africa,Mali,Other,0.57
74,1986,Americas,Bolivia (Plurinational State of),Spirits,2.06
79,1989,Europe,Finland,Other,2.09
80,1985,Africa,Malawi,Other,0.84
82,1987,Europe,Ireland,Spirits,2.25
86,1986,Americas,Bahamas,Wine,1.83
89,1986,Eastern Mediterranean,Lebanon,Wine,0.70