Write a Pandas program to filter all records starting from the 2nd row, access every 5th row from world alcohol consumption dataset.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('world_alcohol - world_alcohol.csv')

In [4]:
filtered_df = df.iloc[1::5]

filtered_df

,Year,WHO region,Country,Beverage Types,Display Value
1,1986,Americas,Uruguay,Other,0.50
6,1987,Africa,Mauritius,Wine,0.13
11,1989,Americas,Guatemala,Beer,0.62
16,1984,Americas,Costa Rica,Wine,0.06
21,1989,Americas,Costa Rica,Spirits,4.51
26,1985,Europe,United Kingdom of Great Britain and Northern I...,Wine,1.36
31,1986,Western Pacific,Micronesia (Federated States of),Wine,0.00
36,1987,Eastern Mediterranean,Egypt,Beer,0.07
41,1986,Europe,Czech Republic,Beer,6.82
46,1987,Americas,Trinidad and Tobago,Spirits,2.26
51,1987,Europe,Finland,Beer,3.88
56,1987,Western Pacific,Viet Nam,Wine,0.00
61,1984,Western Pacific,Papua New Guinea,Spirits,0.08
66,1987,Eastern Mediterranean,Iraq,Wine,0.01
71,1985,Africa,Mali,Other,0.57
76,1985,Africa,Comoros,Beer,0.02
81,1985,Europe,Netherlands,Wine,2.54
86,1986,Americas,Bahamas,Wine,1.83
91,1989,Europe,Bulgaria,Beer,4.43
96,1985,Europe,Luxembourg,Wine,7.38